apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: finance-cost-orchestrator
  app.kubernetes.io/component: orchestrator
  app.kubernetes.io/part-of: goapps
