apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-cost-orchestrator
  labels:
    app: finance-cost-orchestrator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: finance-cost-orchestrator
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
