apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: finance-worker
  app.kubernetes.io/component: worker
  app.kubernetes.io/part-of: goapps
